## Lab 4 - part 2: Data Weights and Autocorellation

**TU Delft and WUR**<br>
**Q1 2024**<br>
**Instructor:** Theodoros Chatzivasileiadis <br>
**Instructor:** Hans Hoogenboom <br>
**TA:** Ka Yi Chua <br>
**[Metropolitan Data 1](https://jhoogenboom.github.io/spatial-data-science/_index.html)** <br>



## Exercise 4a: Spatial Autocorrelation and ESDA 

USE the Liverpool IMD data we have been using in previous sessions. This will require you to:

* Load up the IMD dataset for Liverpool.
* Create a choropleth of the `imd_score` variable.
* Compute the spatial weights matrix for the LSOAs. Think of one criterium to build it that you think would fit this variable (e.g. contiguity, distance-based, etc.), and apply it.
* Create the standardized version of the IMD scores.
* Calculate the spatial lag of the standardized scores.
* Create the Moran Plot.
* Calculate the value of Moran's I as well as its significance level.
* Perform a LISA analysis and generate a map of the results. What are the main patterns?

In [10]:
# your code here


For this part I would like you to experiment with Data from Amstedam. However this will require you to find the dataset yourself!

## Question 1: Building a Contiguity-Based Weight Matrix

Use PySAL to create a contiguity-based weight matrix (W) for a given spatial dataset of polygons. Write a function create_contiguity_weights that:

    Reads in a shapefile of polygons.
    Constructs a Queen contiguity-based spatial weights matrix.
    Returns the weight matrix.

## Question 2: Calculating Moran’s I

Write a function calculate_morans_i that:

    Takes a spatial weight matrix W and an attribute array y.
    Calculates Moran’s I for the given attribute array.
    Returns the Moran’s I value and its p-value.

## Question 3: Standardizing Spatial Weight Matrices

Create a function standardize_weights that:

    Takes a spatial weight matrix W.
    Standardizes it so that the weights of each row sum to one.
    Returns the standardized weight matrix.

## Question 4: Creating Distance-Based Weights

Write a function create_distance_weights that:

    Takes a set of point coordinates and a threshold distance.
    Constructs a distance-based spatial weight matrix where all points within the threshold distance are assigned a weight.
    Returns the weight matrix.

## Question 5: Visualizing a Moran Plot

Using PySAL, write a function plot_moran that:

    Takes a spatial weights matrix W and an attribute array y.
    Creates and displays a Moran plot for the attribute.
    Saves the Moran plot as an image file.

In [14]:
# Question 1: Building a Continuity-Based Weight Matrix

import geopandas as gpd
from libpysal.weights import Queen

file_path = "C:\\Users\\rober\\Downloads\\brexit.gpkg\\brexit.gpkg"

def construct_queen_weight_matrix(file_path):
    gdf = gpd.read_file(file_path)

    gdf = gdf[gdf.is_valid]

    queen_w = Queen.from_dataframe(gdf)

    return queen_w

print(construct_queen_weight_matrix(file_path).full()[0])




C:\Users\rober\AppData\Local\Temp\ipykernel_2976\2072350846.py:13: FutureWarning: `use_index` defaults to False but will default to True in future. Set True/False directly to control this behavior and silence this warning
  queen_w = Queen.from_dataframe(gdf)


[[0. 0. 1. ... 0. 0. 0.]
 [0. 0. 1. ... 0. 0. 0.]
 [1. 1. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 1.]
 [0. 0. 0. ... 0. 1. 0.]]


c:\Users\rober\AppData\Local\Programs\Python\Python312\Lib\site-packages\libpysal\weights\contiguity.py:347: UserWarning: The weights matrix is not fully connected: 
 There are 7 disconnected components.
 There are 6 islands with ids: 45, 51, 331, 339, 342, 358.
  W.__init__(self, neighbors, ids=ids, **kw)


In [23]:
# Question 4: Creating Distance-Based Weights

import numpy as np
from scipy.spatial import distance_matrix
import sys
from scipy.spatial import distance_matrix

def create_distance_weights(coordinates, threshold_distance):
    """
    Creates a distance-based spatial weight matrix.

    Parameters:
    - coordinates: A list or array of point coordinates [(x1, y1), (x2, y2), ...].
    - threshold_distance: The threshold distance to determine neighbors.

    Returns:
    - A distance-based spatial weight matrix (numpy array).
"""

    sys.setrecursionlimit(3000)

    coords_array = np.array(coordinates)

    dist_matrix = distance_matrix(coords_array, coords_array)

    weight_matrix = (dist_matrix <= threshold_distance).astype(int)

    return weight_matrix

In [24]:
coordinates = [
    (0, 0),
    (1, 1),
    (2, 2),
    (3, 3),
    (5, 5),
    (10, 10)
]

threshold_distance = 3.0

print(create_distance_weights(coordinates, threshold_distance))

[[1 1 1 0 0 0]
 [1 1 1 1 0 0]
 [1 1 1 1 0 0]
 [0 1 1 1 1 0]
 [0 0 0 1 1 0]
 [0 0 0 0 0 1]]
